name: mentorship_e1_g3
description: "A new Flutter project."
# publish_to: "none" # Uncomment this line if you don't want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management and Dependency Injection
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  get_it: ^7.6.7
  
  # Networking
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  
  # Firebase Integration
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2
  google_sign_in: ^6.2.1
  country_code_picker: ^3.0.0
  
  # UI Components
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.0
  
  cached_network_image: ^3.3.1


  # Code Generation and Serialization
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  
  # Logging
  pretty_dio_logger: ^1.3.1
  lottie: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Faster Data Model Development
  build_runner: ^2.4.9

  # Animatied packges 
  hero_animation: ^1.1.4

flutter:
  uses-material-design: true
  assets:
  # Images :
    - assets/images/
    - assets/animations/
    - assets/animations/signup/
    - assets/images/login_screen/
    - assets/images/login_screen/social_icons/
    - assets/images/splash/
    - assets/images/home/
    - assets/images/home/rocket.png
    - assets/images/home/profile.png
  
  # Animations :
    - assets/animations/
    - assets/animations/onboarding/
    - assets/animations/splash/