name: spacexx
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Statemangment 
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5

  # Networking
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  flutter_offline: ^3.0.1
  shared_preferences: ^2.2.3
  
  # UI
  cached_network_image: ^3.3.1
  country_code_picker: ^3.0.0
  crystal_navigation_bar: ^1.0.0
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.0
  hero_animation: ^1.1.4
  google_fonts: ^6.2.0
  slide_countdown: ^1.6.1
  flutter_native_splash: ^2.4.0
  carousel_slider: ^4.2.1
  device_preview: ^1.1.0
  youtube_player_flutter: ^8.0.0
  flutter_inappwebview: ^5.3.2


# Firebase
  firebase_auth: ^4.6.3
  firebase_core: ^2.13.1
  google_sign_in: ^6.2.1
  
  # DI
  get_it: ^7.6.7
  
  # Code Generation and Serialization
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.9


  #web view 
  webview_flutter: ^2.0.13


  flutter_lints: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true
  assets:
    # Images :
    - assets/images/
    - assets/images/login/
    - assets/images/signup/
    - assets/images/login/social_icons/
    - assets/images/splash/
    - assets/images/home/

    # Animations :
    - assets/animation/
    - assets/animation/onboarding/
    - assets/animation/splash/
    - assets/animation/signup/
    - assets/animation/splash/SpacexSplash.lottie
  

  fonts:
    - family: Schibsted Grotesk
      fonts:
        - asset: assets/fonts/SchibstedGrotesk-Bold.ttf
        - asset: assets/fonts/SchibstedGrotesk-SemiBold.ttf
        - asset: assets/fonts/SchibstedGrotesk-Medium.ttf
