name: mentorship_e1_g3
description: "A new Flutter project."
# publish_to: "none" # Uncomment this line if you don't want to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  country_code_picker: ^3.0.0
  crystal_navigation_bar: ^1.0.0
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1



  # Code Generation and Serialization

  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  google_fonts: ^6.2.0
  google_sign_in: ^6.2.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  lottie: ^3.1.0
  pretty_dio_logger: ^1.3.1

  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  slide_countdown: ^1.6.1

  
  flutter_native_splash: ^2.4.0


  #Flutter Offline
  flutter_offline: ^3.0.1

dev_dependencies:
  # Faster Data Model Development
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

  # Animatied packges
  hero_animation: ^1.1.4

  #UI componanets 
  carousel_slider: ^4.2.1

  #web view 
  webview_flutter: ^2.0.13

flutter:
  uses-material-design: true
  assets:
    # Images :
    - assets/images/
    # Animations :
    - assets/animations/
    - assets/animations/onboarding/
    - assets/animations/splash/
    - assets/animations/signup/
    - assets/animation/
    - assets/animation/error404.json
    - assets/animation/log_out.json
    - assets/images/login_screen/
    - assets/images/login_screen/social_icons/
    - assets/images/splash/
    - assets/images/home/
    - assets/images/home/rocket.png
    - assets/images/home/profile.png
    - assets/animation/not_intrnet_connection.json
    - assets/animations/splash/SpacexSplash.lottie
  

  fonts:
    - family: Schibsted Grotesk
      fonts:
        - asset: assets/fonts/SchibstedGrotesk-Bold.ttf
        - asset: assets/fonts/SchibstedGrotesk-SemiBold.ttf
        - asset: assets/fonts/SchibstedGrotesk-Medium.ttf
